name: Deploy to beta
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: assemblebeta
          REMOTE_PATH: "wp-content/themes/assemble-theme/"
          PHP_LINT: TRUE
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
          CACHE_CLEAR: TRUE
